### ISSUE TITLE
Incompatible with Gnome 40

### ISSUE THREAD

**Issue by josemotanet** [goloshubov/tp-comp-keyboard-fnlk-switch#1]
Hello,

I'd like to report that this extension is incompatible with Gnome 40. I'm not exactly sure how to go about the upgrade process but I'm happy to assist wherever possible, should I be able.

**Comment by josemotanet** [comment]
Perhaps this line requires a reference to 40?

https://github.com/goloshubov/fnlock-switch-tp-comp-usb-kb/blob/4423df53353d81d59dcc47f3e6a16c45dadf1943/fnlock-switch-tp-comp-usb-kb%40goloshubov.github.io/metadata.json#L6

**Comment by goloshubov** [comment]
Hi Jose,
Thank you for noticing this. I've just added version 40 to the list.

**Comment by josemotanet** [comment]
This is great, I'm happy I could help :+1:
