### ISSUE TITLE
Support keyboard shortcuts to toggle the state

### ISSUE THREAD

**Issue by crystalcommunication** [goloshubov/tp-comp-keyboard-fnlk-switch#5]
It would be nice if there was a way to add a keyboard shortcut to toggle the FnLk state. I have successfully used various other methods to bind the underlying script to a keyboard shortcut, but that doesn't cause the indicator in the panel to be updated.

It would be really great if we could make the extension handle the KEY_FN_ESC event. This is tricky, because the event appears to be emitted from the TrackPoint's event handle in /dev/input instead of the keyboard for some reason, but it should be possible to compensate for that.

**Comment by goloshubov** [comment]
Thanks for proposal. I was thinking to add keyboard shortcut support in some way, but unfortunately do not have time for this task now. I'll cycle back on this a bit later.

**Comment by goloshubov** [comment]
Keybinding support is added. By default it is Ctrl+Esc (max close to Fn+Esc).
Custom keybinding will be available after adding preferences, but it can be customized now by adding and editing it in dconf:

```bash
cat << EOF | dconf load /org/gnome/shell/extensions/fnlock/
[/]
keybinding=['<Control>Escape']
EOF
```
